### Jane Street Puzzles: Die Agony

In [3]:
import numpy as np
from sys import exit

In [8]:
# Init board
board = np.array(
    [[57,33,132,268,492,732],
    [81,123,240,443,353,508],
    [186,42,195,704,452,228],
    [-7,2,357,452,317,395],
    [5,23,-4,592,445,620],
    [0,77,32,403,337,452]], dtype=int)

# Init starting position
pos_row=5
pos_col=0

# Init score
score = np.array([0])

# Init die
die = np.array([0,0,0,0,0,0])

# Display starting setup
print(f"Board: \n{board}")
print(f"Score: {score}")
print(f"Die: {die}")

next_step_of_procedure(step=1, act_pos_row=pos_row, act_pos_col=pos_col, score=score, die=die)

Board: 
[[ 57  33 132 268 492 732]
 [ 81 123 240 443 353 508]
 [186  42 195 704 452 228]
 [ -7   2 357 452 317 395]
 [  5  23  -4 592 445 620]
 [  0  77  32 403 337 452]]
Score: [0]
Die: [0 0 0 0 0 0]

Step 1
Currently we are in (5/0) = 0
The current score is [0]
The current die is [0 0 0 0 0 0]
Possible new board values = {'N': 5, 'E': 77}
Go N
New die value 5.0 can be used
Update die with 5.0
Update score with 5.0

Step 2
Currently we are in (4/0) = 5
The current score is [0. 5.]
The current die is [5 0 0 0 0 0]
Possible new board values = {'N': -7, 'E': 23, 'S': 0}
Go N
New die value -6.0 can be used
Update die with -6.0
Update score with -7.0

Step 3
Currently we are in (3/0) = -7
The current score is [ 0.  5. -7.]
The current die is [ 5 -6  0  0  0  0]
Possible new board values = {'N': 186, 'E': 2, 'S': 5}
Go N
N is a DEADEND
Go E
Field -6 of die can be used!

Step 3
Currently we are in (4/1) = 23
The current score is [ 0.  5. -7. -7.]
The current die is [ 5 -6  0  0  0  0]
Possib

In [5]:
def get_moving_options(pos_row, pos_col):
    
    moving_options_dict = {}
    
    # Check where the die can go [N,E,S,W]
    # North
    if pos_row>=1:
        moving_options_dict.update({'N': board[pos_row-1, pos_col]})
    # East
    if pos_col<=4:
        moving_options_dict.update({'E': board[pos_row, pos_col+1]})
    # South
    if pos_row<=4:
        moving_options_dict.update({'S': board[pos_row+1, pos_col]})
    # West
    if pos_col>=1:
        moving_options_dict.update({'W': board[pos_row, pos_col-1]})
        
    return moving_options_dict

In [7]:
def next_step_of_procedure(step, act_pos_row, act_pos_col, score, die):
           
    print("")
    
    # Print actual step
    print(f"Step {step}")
    
    # Print actual position
    print(f"Currently we are in ({act_pos_row}/{act_pos_col}) = {board[act_pos_row,act_pos_col]}")

    # Print actual score
    print(f"The current score is {score}")

    # Print actual die
    print(f"The current die is {die}")
    
    max_step = 1000
    if step > max_step:
        print("Maximum step reached!")
        exit()
    
    if board[act_pos_row,act_pos_col] == 732:
        print("Endpoint reached!")
        exit()

    # Get moving options
    moving_options = get_moving_options(act_pos_row, act_pos_col)
    print(f"Possible new board values = {moving_options}")

    # Check all possible new board values
    for direction, new_pos in moving_options.items():
        
        print(f"Go {direction}")
        
        # Check if one of the die values can be used
        for die_value in die[die!=0]:
                        
            if score.size > step and score[step] == score[step-1] + step * die_value:

                #print(f"score[i] = {score[step]}")
                #print(f" score[i-1] + i * die_value = {score[step-1] + step * die_value}")

                # Die value can be used!
                print(f"Field {die_value} of die can be used!")
                # Update score
                score = np.append(score, score[step-1] + step * die_value)

                # Update position
                if direction=='N':
                    new_pos_row = act_pos_row-1
                    new_pos_col = act_pos_col
                elif direction=='E':
                    new_pos_row = act_pos_row
                    new_pos_col = act_pos_col+1
                elif direction=='S':
                    new_pos_row = act_pos_row+1
                    new_pos_col = act_pos_col
                elif direction== 'W':
                    new_pos_row = act_pos_row
                    new_pos_col = act_pos_col-1

                # Run next step
                next_step_of_procedure(step+1, new_pos_row, new_pos_col, score, die)

        # Check if die still has open values
        if 0 in die:

            # Get new die value
            new_die_value = (new_pos - score[step-1]) / step
            
            # Check if new die value is an integer
            if new_die_value % round(new_die_value) == 0:
                
                print(f"New die value {new_die_value} can be used")
                
                # Update die
                print(f"Update die with {new_die_value}")
                die[np.where(die==0)[0][0]] = new_die_value

                # Update score
                print(f"Update score with {score[step-1] + step * new_die_value}")
                score = np.append(score, score[step-1] + step * new_die_value)

                # Update position
                if direction=='N':
                    new_pos_row = act_pos_row-1
                    new_pos_col = act_pos_col
                elif direction=='E':
                    new_pos_row = act_pos_row
                    new_pos_col = act_pos_col+1
                elif direction=='S':
                    new_pos_row = act_pos_row+1
                    new_pos_col = act_pos_col
                elif direction== 'W':
                    new_pos_row = act_pos_row
                    new_pos_col = act_pos_col-1

                # Run next step
                next_step_of_procedure(step+1, new_pos_row, new_pos_col, score, die)
            
            else:
                print(f"{direction} is a DEADEND")
                step=1
                break
            
        else:
            print(f"{direction} is a DEADEND")
            step=1
            break
            

In [151]:
die[die!=0]

array([ 5, -6])